# Generated by Django 3.2.7 on 2022-02-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220222_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
